
import iphoneImage from "../assets/iphone.jpg";
import galaxyImage from "../assets/galaxy.jpg";
import oneplusImage from "../assets/oneplus.jpg";
import iphone1Image from "../assets/iphone 1.jpg";

// Updated mobiles array with imported images
const mobiles = [
  {
    id: 1,
    name: "iPhone 14",
    image: iphoneImage,
    price: "₹61,900",
    mrp: "₹79,900",
    discount: "23% off",
    rating: "★★★★☆ 3,151",
    delivery: "FREE delivery Sat, 22 Mar",
  },
  {
    id: 2,
    name: "Samsung Galaxy S23",
    image: galaxyImage,
    price: "₹74,999",
    mrp: "₹89,999",
    discount: "17% off",
    rating: "★★★★★ 2,568",
    delivery: "FREE delivery Thu, 21 Mar",
  },
  {
    id: 3,
    name: "Samsung Galaxy S23",
    image: galaxyImage,
    price: "₹74,999",
    mrp: "₹89,999",
    discount: "17% off",
    rating: "★★★★★ 2,568",
    delivery: "FREE delivery Thu, 21 Mar",
  },
  {
    id: 4,
    name: "Samsung Galaxy S23",
    image: iphone1Image,
    price: "₹74,999",
    mrp: "₹89,999",
    discount: "17% off",
    rating: "★★★★★ 2,568",
    delivery: "FREE delivery Thu, 21 Mar",
  },
  {
    id: 5,
    name: "Samsung Galaxy S23",
    image: iphone1Image,
    price: "₹74,999",
    mrp: "₹89,999",
    discount: "17% off",
    rating: "★★★★★ 2,568",
    delivery: "FREE delivery Thu, 21 Mar",
  },
  {
    id: 6,
    name: "Samsung Galaxy S23",
    image: oneplusImage,
    price: "₹74,999",
    mrp: "₹89,999",
    discount: "17% off",
    rating: "★★★★★ 2,568",
    delivery: "FREE delivery Thu, 21 Mar",
  },
  {
    id: 7,
    name: "Samsung Galaxy S23",
    image: oneplusImage,
    price: "₹74,999",
    mrp: "₹89,999",
    discount: "17% off",
    rating: "★★★★★ 2,568",
    delivery: "FREE delivery Thu, 21 Mar",
  },
  {
    id: 8,
    name: "Samsung Galaxy S23",
    image: oneplusImage,
    price: "₹74,999",
    mrp: "₹89,999",
    discount: "17% off",
    rating: "★★★★★ 2,568",
    delivery: "FREE delivery Thu, 21 Mar",
  },
  {
    id: 9,
    name: "Samsung Galaxy S23",
    image: iphoneImage,
    price: "₹74,999",
    mrp: "₹89,999",
    discount: "17% off",
    rating: "★★★★★ 2,568",
    delivery: "FREE delivery Thu, 21 Mar",
  },
  {
    id: 10,
    name: "Samsung Galaxy S23",
    image: galaxyImage,
    price: "₹74,999",
    mrp: "₹89,999",
    discount: "17% off",
    rating: "★★★★★ 2,568",
    delivery: "FREE delivery Thu, 21 Mar",
  },
];
  export default mobiles;
